### ISSUE TITLE
镜像内部加载GPU成功但TensorFlow无法调用

### ISSUE THREAD

**Issue by linstein** [DvcLAB/JupyterLab-Inst#15]
1. 镜像内部可以使用nvidia-smi显示nvidia信息，但当使用`tf.test.is_gpu_available()`时，结果为False，提示failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error。
2. 通过nvidia-smi查看的nvidia-driver信息，显示对应的CUDA版本为11.2，而此镜像使用的CUDA是10.1
![image](https://user-images.githubusercontent.com/38755884/113823502-4eae8d80-97b1-11eb-84b1-14204ac24664.png)
![image](https://user-images.githubusercontent.com/38755884/113823604-6dad1f80-97b1-11eb-9200-c6c95a870d98.png)
3. 推测是宿主机nvidia-driver的更新导致与CUDA版本不对应

**Comment by linstein** [comment]
目前使用的tf2.2版本对应10.1的CUDA版本，目前还没有TensorFlow对应CUDA11.2的版本
参考：[TensorFlow GPU的版本对应关系](https://tensorflow.google.cn/install/source#gpu)

**Comment by linstein** [comment]
1. 卸载原有nvidia-driver
```
apt-get --purge remove nvidia*
apt autoremove
apt-get --purge remove "*cublas*" "cuda*"
apt-get --purge remove "*nvidia*"
```
2. 安装新的nvidia-driver
```
apt install nvidia-driver-435
#弹出提示设置boot时的密码  123456789
reboot
```
目前连接不上机器

**Comment by linstein** [comment]
应该由于secure boot的原因，在安装过程中会提示设置一个密码，在重启时需要输入密码验证以禁用secure boot，重启后会出现蓝屏，这时候不能直接选择continue,而应该按下按键，选择Enroll MOK, 确认后在下一个选项中选择continue,接着输入安装驱动时设置的密码，开机。

**Comment by linstein** [comment]
通过重装nvidia-driver解决了问题
